on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: yarn && yarn add typescript && yarn add ts-node
      - name: Build
        run: yarn test && yarn start
      - name: Sucess
        run: echo "Success🎉"
